import type { Task } from '@/lib/types';
import { TaskStatus, TaskPriority, OwnerType } from '@/lib/constants';

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Define runtime adapter interface',
    description: 'Create the TypeScript interface for the RuntimeAdapter per 03_RUNTIME_CONTRACT.md. Include stub implementation.',
    status: TaskStatus.DONE,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-axel',
    priority: TaskPriority.HIGH,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Draft acceptance criteria for task system',
    description: 'Write acceptance criteria for the Kanban board, task creation, task assignment, and status transitions.',
    status: TaskStatus.REVIEW,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-riff',
    priority: TaskPriority.MEDIUM,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-16T09:00:00Z',
    updatedAt: '2026-01-22T11:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Test plan for persona override system',
    description: 'Generate regression risk map, test scenarios, and edge cases for the layered persona override system.',
    status: TaskStatus.IN_PROGRESS,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-torque',
    priority: TaskPriority.HIGH,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-17T08:30:00Z',
    updatedAt: '2026-01-23T09:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Implement RBAC permission matrix',
    description: 'Set up the 5-role permission system with Supabase RLS policies and server-side checks.',
    status: TaskStatus.READY,
    ownerType: OwnerType.HUMAN,
    ownerId: 'user-spencer',
    priority: TaskPriority.CRITICAL,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Audit log viewer UI',
    description: 'Build the filterable audit log table with columns: timestamp, actor, action, entity, reason.',
    status: TaskStatus.BACKLOG,
    ownerType: OwnerType.HUMAN,
    ownerId: 'user-spencer',
    priority: TaskPriority.MEDIUM,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-19T10:00:00Z',
    updatedAt: '2026-01-19T10:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Seed MVP agent data',
    description: 'Create database seed script for Axel, Riff, and Torque with base persona metadata.',
    status: TaskStatus.WAITING,
    ownerType: OwnerType.HUMAN,
    ownerId: 'user-spencer',
    priority: TaskPriority.LOW,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-21T16:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Risk assessment for auth flow',
    description: 'Identify risks in the Supabase auth integration: session handling, role validation, RLS policy gaps.',
    status: TaskStatus.IN_PROGRESS,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-axel',
    priority: TaskPriority.HIGH,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-21T09:00:00Z',
    updatedAt: '2026-01-24T10:00:00Z',
  },
  {
    id: 'task-8',
    title: 'SOW alignment check for Phase 1 scope',
    description: 'Verify Phase 1 deliverables align with the original scope-of-work. Flag any scope drift.',
    status: TaskStatus.BACKLOG,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-riff',
    priority: TaskPriority.LOW,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Design system compliance audit',
    description: 'Verify all pages follow 01_DESIGN_GUIDE.md: dark theme, monochrome palette, MUI-only components, no gradients.',
    status: TaskStatus.READY,
    ownerType: OwnerType.AGENT,
    ownerId: 'agent-torque',
    priority: TaskPriority.MEDIUM,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-23T10:00:00Z',
    updatedAt: '2026-01-23T10:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Knowledge source metadata model',
    description: 'Implement KnowledgeSource entity with name, type, path fields. Build list view in admin.',
    status: TaskStatus.BACKLOG,
    ownerType: OwnerType.HUMAN,
    ownerId: 'user-spencer',
    priority: TaskPriority.LOW,
    projectTag: 'fullthrottle',
    runtimeRunId: null,
    lastRuntimeStatus: null,
    createdBy: 'user-spencer',
    createdAt: '2026-01-24T10:00:00Z',
    updatedAt: '2026-01-24T10:00:00Z',
  },
];
