import type { AuditLogEntry } from '@/lib/types';

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'audit-1',
    actorId: 'user-spencer',
    actorName: 'Spencer',
    actionType: 'persona_override_created',
    entityType: 'PersonaOverride',
    entityId: 'override-1',
    beforeState: null,
    afterState: { version: 'v1.0', scopeType: 'agent', agentId: 'agent-axel' },
    reason: 'Initial persona override configuration for Axel engineering agent',
    timestamp: '2026-01-10T10:00:00Z',
  },
  {
    id: 'audit-2',
    actorId: 'user-spencer',
    actorName: 'Spencer',
    actionType: 'persona_override_created',
    entityType: 'PersonaOverride',
    entityId: 'override-2',
    beforeState: null,
    afterState: { version: 'v1.0', scopeType: 'project', agentId: 'agent-riff' },
    reason: 'Project-scoped override for Riff on FullThrottle project',
    timestamp: '2026-01-12T10:00:00Z',
  },
  {
    id: 'audit-3',
    actorId: 'user-spencer',
    actorName: 'Spencer',
    actionType: 'agent_status_changed',
    entityType: 'Agent',
    entityId: 'agent-axel',
    beforeState: { status: 'planned' },
    afterState: { status: 'offline' },
    reason: 'Agent registered, awaiting runtime connection',
    timestamp: '2026-01-15T10:00:00Z',
  },
  {
    id: 'audit-4',
    actorId: 'user-spencer',
    actorName: 'Spencer',
    actionType: 'task_created',
    entityType: 'Task',
    entityId: 'task-1',
    beforeState: null,
    afterState: { title: 'Define runtime adapter interface', status: 'backlog' },
    reason: 'Created initial task for runtime adapter work',
    timestamp: '2026-01-15T10:30:00Z',
  },
  {
    id: 'audit-5',
    actorId: 'user-spencer',
    actorName: 'Spencer',
    actionType: 'persona_override_approved',
    entityType: 'PersonaOverride',
    entityId: 'override-3',
    beforeState: { approvedBy: null },
    afterState: { approvedBy: 'user-spencer' },
    reason: 'Approved staging environment override for Torque QA agent',
    timestamp: '2026-01-14T14:00:00Z',
  },
];
